name:                mp1-haskell
version:             0.1.0.0
license:             BSD3
author:              "Mattox Beckman"
maintainer:          "mattox@illinois.edu"
copyright:           "2015-2020 Mattox Beckman"

dependencies:
- base >= 4.7 && < 5

tests:
  tests-test:
    main:                Spec.hs
    source-dirs:
    - test
    - src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - unordered-containers
    - QuickCheck
    - HUnit
    - test-framework
    - test-framework-hunit
    - test-framework-quickcheck2
